<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="UTF-8">
    <link rel="shortcut icon" href="/pics/logo.png" type="image/png">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="Cache-Control" content="no-cache" />
		<link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="/js/jquery/jquery-ui.css">
    <link rel="stylesheet" href="/css/main.css">
    <script src="/js/jquery/jquery.min.js" type="text/javascript"></script>
    <script src="/js/jquery/jquery-ui.min.js" type="text/javascript"></script>
    <script src="/js/main.js"></script>
    <title>Копицентр</title>
  </head>
  <body>