<?=$this->ib('header')?>
<content class="fc_top">
  <center style="width:100%;height: 100%;">
    <div class="fc_top">
      <div id="op_header">Электронная очередь</div>
			<div class="fc_center" style="width: 100%;padding: 0 60px;">
				<div id="op_cont" class="fr_sparound" style="width:100%">
					<div id="op_printed">
						<div>Идёт печать чека...</div>
						<img src="/pics/printed.png"/>
					</div>
					<div id="op_usr1" onclick="oq.registerUser(1,true)" class="btn"><span>ОФОРМИТЬ ЗАКАЗ</span></div>
					<div id="op_usr2" onclick="oq.registerUser(2,true)" class="btn"><span>ЗАБРАТЬ ЗАКАЗ</span></div>
				</div>
			</div>
    </div>
  </center>
</content>
<?=$this->ib('footer')?>
<script>

</script>